//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zavod
{
    using System;
    using System.Collections.Generic;
    
    public partial class Yslyga
    {
        public int Id_Yslygi { get; set; }
        public int Id_Obor { get; set; }
        public int Id_sotr { get; set; }
        public int Id_Otdela { get; set; }
        public System.DateTime Date_Yslygi { get; set; }
        public string Name_Yslygi { get; set; }
    
        public virtual Obor Obor { get; set; }
        public virtual Otdel Otdel { get; set; }
        public virtual Sotr Sotr { get; set; }
    }
}
